name: Google Indexing Automation

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  google-indexing:
    runs-on: ubuntu-latest
    steps:
      - name: Send Sitemap to Google Indexing API
        uses: robingenz/action-google-indexing@v1.0.0
        with:
          siteUrl: 'https://resumeforge.alfo.online'
          gcpServiceAccountKey: ${{ secrets.GCP_SA_KEY }}
